# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ICBjLnF1jeoHtIfoK8rTlATMp-OnRAxg
"""

import numpy as np
import pickle
import pandas as pd
import streamlit as st
from tensorflow import keras
from keras.preprocessing.text import Tokenizer
import nltk
# Importing the libraries
from keras.utils.data_utils import pad_sequences

from numpy import loadtxt
from tensorflow.keras.models import load_model
 
# load model
classifier = load_model('model11.h5')

filenametoken = 'mod.pkl'
token = pickle.load(open(filenametoken, 'rb'))

def predict(text): #input is from forms
    Sentence = text
    text = token.texts_to_sequences(Sentence)
    text = pad_sequences(text, maxlen=250,dtype='int32', value=0)
    print(text)
    sentiment = classifier.predict(text,batch_size=1,verbose = 2)[0]
    print(sentiment)
    y_predicted = sentiment.flatten()
    y_predicted = np.where(y_predicted > 0.5, 1, 0)
    print(y_predicted)
    if y_predicted[0]==1:
      return "Negative"
    elif y_predicted[1]==1:
      return "Nuetral"
    elif y_predicted[2]==1:
      return "Positive"


def main():
  image = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB0zmSqBc5MOOoz9uyPCH-oEuPm65Tw1Xwfg&usqp=CAU'
  st.image(image,use_column_width=False)

  add_selectbox = st.selectbox("How would you like to predict?",("Sentence", "Batch File"))

  st.title("Sentiment Analysis App")
  html_temp = """
   # <div style="background-color:tomato;padding:10px">
    <h2 style="color:white;text-align:center;">Finanacial sentiment analysis ML App </h2>
    </div>
    """
  if add_selectbox == 'Sentence':
      st.markdown(html_temp,unsafe_allow_html=True)
      Sentence = st.text_input("Enter Text",key ="account_lenght")  
      raw_text = [Sentence]
    
      result=""
      if st.button("Predict"):
          result=predict(raw_text)
      st.success('{}'.format(result))
if __name__=='__main__':
    main()